//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shootapp
{
    using System;
    using System.Collections.Generic;
    
    public partial class competitionview
    {
        public long comid { get; set; }
        public long shoid { get; set; }
        public string shoname { get; set; }
        public string shosname { get; set; }
        public Nullable<long> teaid { get; set; }
        public string teaname { get; set; }
        public Nullable<long> shots { get; set; }
        public Nullable<long> score { get; set; }
        public string hits { get; set; }
        public Nullable<long> penal { get; set; }
    }
}
