//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shootapp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShootappDBEntities : DbContext
    {
        public ShootappDBEntities()
            : base("name=ShootappDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<competition> competitions { get; set; }
        public virtual DbSet<result> results { get; set; }
        public virtual DbSet<shooter> shooters { get; set; }
        public virtual DbSet<team> teams { get; set; }
        public virtual DbSet<competitionview> competitionviews { get; set; }
        public virtual DbSet<shooterscoview> shooterscoviews { get; set; }
        public virtual DbSet<singleprintview> singleprintviews { get; set; }
        public virtual DbSet<teamdistview> teamdistviews { get; set; }
        public virtual DbSet<teamprintview> teamprintviews { get; set; }
    }
}
