//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shootapp
{
    using System;
    using System.Collections.Generic;
    
    public partial class shooterscoview
    {
        public long id { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public Nullable<long> tid { get; set; }
        public string note { get; set; }
        public string tname { get; set; }
    }
}
