//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shootapp
{
    using System;
    using System.Collections.Generic;
    
    public partial class teamprintview
    {
        public long cid { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public Nullable<long> tid { get; set; }
        public string tname { get; set; }
        public Nullable<long> shots { get; set; }
        public Nullable<long> score { get; set; }
        public string hits { get; set; }
        public long sid { get; set; }
        public long cstotal { get; set; }
        public Nullable<long> penal { get; set; }
    }
}
